theme = "docs-balsamiq-com"
 baseUrl =  "/"
 relativeUrls = true
# baseurl =  "http://localhost:1313/"
languageCode =  "en-us"
title =  "Documentation"
MetaDataFormat =  "yaml"
pluralizeListTitles =  false
Paginate =  "50"
PageSize =  "50"
contentdir =  "content"
layoutdir =  "layouts"
publishdir =  "public"
[params]
 ssdocs1url = "https://mmclssg1.github.io/ssdocs"
#  ssdocs1url = "http://localhost:1313/ssdocs/"

[blackfriday]
  plainIdAnchors = true

[taxonomies]
  category =  "categories"
  tag =  "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
