theme = "docs-balsamiq-com"
baseurl =  "https://mmclssg1.github.io/ssdocs"
languageCode =  "en-us"
title =  "Documentation"
MetaDataFormat =  "yaml"
pluralizeListTitles =  false
Paginate =  "50"
PageSize =  "50"
contentdir =  "content"
layoutdir =  "layouts"
publishdir =  "public"
[params]
 ssdocs1url = "https://mmclssg1.github.io/ssdocs"
 # ssdocs2url = "https://mmclssg1.github.io"
#   ssdocs1url = "https://localhost:1313"

[blackfriday]
  plainIdAnchors = true

[taxonomies]
  category =  "categories"
  tag =  "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
